export const ordersDashboardTokens = {
  stack: 'space-y-6',
  panel: 'bg-white border border-gray-200 rounded-lg',
  emptyPanel: 'text-center py-8 bg-white rounded-lg border border-gray-200',
  headerRow: 'flex items-center justify-between',
  message: 'p-3 rounded-lg text-sm',
  statsGridDefault: 'grid grid-cols-2 md:grid-cols-5 gap-4',
  statsGridWide: 'grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-4',
  statCard: 'p-4 rounded-lg border',
  toolbar: 'flex flex-wrap items-end gap-3 bg-white border border-gray-200 rounded-lg px-4 py-3',
  sectionDivider: 'w-px h-8 bg-gray-200 self-end hidden sm:block',
  selectBase: 'pl-3 pr-8 py-1.5 text-sm rounded-lg border border-gray-300 bg-white text-gray-700 focus:outline-none cursor-pointer',
  inputBase: 'px-3 py-1.5 rounded-lg text-sm border border-gray-300 bg-white focus:outline-none',
  actionSecondary: 'px-3 py-1.5 text-xs font-medium rounded-lg bg-gray-100 text-gray-600 transition-colors border border-gray-200',
  listContainer: 'space-y-3',
  orderCard: 'bg-white border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow cursor-pointer',
  modalCard: 'bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto',
  kanbanWrap: 'overflow-x-auto pb-3 [scrollbar-gutter:stable]',
  kanbanLane: 'w-[200px] flex-shrink-0 flex flex-col',
  kanbanLaneHeader: 'px-3 py-2 rounded-t-lg font-semibold text-sm flex items-center justify-between',
  kanbanLaneBody: 'bg-gray-50 rounded-b-lg border border-t-0 border-gray-200 flex-1 min-h-[180px] p-2 space-y-2',
  kanbanCard: 'bg-white border rounded-lg p-3 cursor-pointer hover:shadow-md transition-shadow',
}
